[api]
bind = "127.0.0.1:3000"
cors_origin = "http://127.0.0.1:5173"

[collector]
interval = 5
records = 10

[status]
services = [
    { label = "API", endpoint = "https://api.cipherfiles.com/health" },
    { label = "Website", endpoint = "https://cipherfiles.com" },
]
