# TODO(hito): config documentation

[api]
bind = "127.0.0.1:3001"

[collector]
interval = 60
records = 10

[status]
services = [
    { label = "API", endpoint = "https://api.cipherfiles.com/health" },
    { label = "Website", endpoint = "https://cipherfiles.com" },
]
